### ISSUE TITLE
Can't Download Stories (Assertion Error: No result?)

### ISSUE THREAD

**Issue by Cadenia** [Moist-Cat/AIDScrapper#4]
I have already logged in my AIDungeon account via the 'python manage.py register' command; however, whenever I attempt to utilize the download commands, this happens (w/ redacted infomation):

C:\Users\(username)>python manage.py stories -p aid
2022-02-05 21:17:51,347 [INFO] -- user_info.BaseClient: Aid successfully initialized.
2022-02-05 21:17:51,347 [INFO] -- user_info.BaseClient: Trying to log-in via file...
2022-02-05 21:17:51,582 [INFO] -- user_info.BaseClient: User "(name)" sucessfully logged into AID
2022-02-05 21:17:55,499 [INFO] -- user_info.BaseClient: Loaded story: "(Story 1)"
2022-02-05 21:17:55,600 [INFO] -- user_info.BaseClient: Loaded story: "(Story 2)"
2022-02-05 21:17:55,758 [INFO] -- user_info.BaseClient: Loaded story: "(Story 3)"
2022-02-05 21:17:55,758 [DEBUG] -- user_info.BaseClient: Got 3 stories so far
Traceback (most recent call last):
  File "C:\Users\(username)\manage.py", line 60, in <module>
    get_command()
  File "C:\Users\(username)\manage.py", line 48, in get_command
    command(*required_args)
  File "C:\Users\(username)\AppData\Local\Programs\Python\Python310\lib\site-packages\aids\commands.py", line 40, in stories
    self.get_stories()
  File "C:\Users\(username)\AppData\Local\Programs\Python\Python310\lib\site-packages\aids\app\client.py", line 227, in get_stories
    assert result, "No result?"
AssertionError: No result?

This also happens with the 'all' command. It can find and name the stories but it just won't download them, even though I've tried over and over. Is there something I'm missing on my end?

**Comment by Moist-Cat** [comment]
I think I tracked down the issue but some tests seem to be failing after I made the fix, and I don't have the time to see what is going on.
You can use the original script or downgrade to an earlier release. 

>https://jtvjan.nl/aidungeon/

The original doesn't download the WI anymore, though.
